// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/reflection/v1/reflection.proto

package cosmos.reflection.v1;

public final class Reflection {
  private Reflection() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FileDescriptorsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.reflection.v1.FileDescriptorsRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * FileDescriptorsRequest is the Query/FileDescriptors request type.
   * </pre>
   *
   * Protobuf type {@code cosmos.reflection.v1.FileDescriptorsRequest}
   */
  public static final class FileDescriptorsRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.reflection.v1.FileDescriptorsRequest)
      FileDescriptorsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileDescriptorsRequest.newBuilder() to construct.
    private FileDescriptorsRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileDescriptorsRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileDescriptorsRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileDescriptorsRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.reflection.v1.Reflection.internal_static_cosmos_reflection_v1_FileDescriptorsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.reflection.v1.Reflection.internal_static_cosmos_reflection_v1_FileDescriptorsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.reflection.v1.Reflection.FileDescriptorsRequest.class, cosmos.reflection.v1.Reflection.FileDescriptorsRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.reflection.v1.Reflection.FileDescriptorsRequest)) {
        return super.equals(obj);
      }
      cosmos.reflection.v1.Reflection.FileDescriptorsRequest other = (cosmos.reflection.v1.Reflection.FileDescriptorsRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.reflection.v1.Reflection.FileDescriptorsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * FileDescriptorsRequest is the Query/FileDescriptors request type.
     * </pre>
     *
     * Protobuf type {@code cosmos.reflection.v1.FileDescriptorsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.reflection.v1.FileDescriptorsRequest)
        cosmos.reflection.v1.Reflection.FileDescriptorsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.reflection.v1.Reflection.internal_static_cosmos_reflection_v1_FileDescriptorsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.reflection.v1.Reflection.internal_static_cosmos_reflection_v1_FileDescriptorsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.reflection.v1.Reflection.FileDescriptorsRequest.class, cosmos.reflection.v1.Reflection.FileDescriptorsRequest.Builder.class);
      }

      // Construct using cosmos.reflection.v1.Reflection.FileDescriptorsRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.reflection.v1.Reflection.internal_static_cosmos_reflection_v1_FileDescriptorsRequest_descriptor;
      }

      @java.lang.Override
      public cosmos.reflection.v1.Reflection.FileDescriptorsRequest getDefaultInstanceForType() {
        return cosmos.reflection.v1.Reflection.FileDescriptorsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public cosmos.reflection.v1.Reflection.FileDescriptorsRequest build() {
        cosmos.reflection.v1.Reflection.FileDescriptorsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cosmos.reflection.v1.Reflection.FileDescriptorsRequest buildPartial() {
        cosmos.reflection.v1.Reflection.FileDescriptorsRequest result = new cosmos.reflection.v1.Reflection.FileDescriptorsRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.reflection.v1.Reflection.FileDescriptorsRequest) {
          return mergeFrom((cosmos.reflection.v1.Reflection.FileDescriptorsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.reflection.v1.Reflection.FileDescriptorsRequest other) {
        if (other == cosmos.reflection.v1.Reflection.FileDescriptorsRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.reflection.v1.Reflection.FileDescriptorsRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.reflection.v1.Reflection.FileDescriptorsRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.reflection.v1.FileDescriptorsRequest)
    }

    // @@protoc_insertion_point(class_scope:cosmos.reflection.v1.FileDescriptorsRequest)
    private static final cosmos.reflection.v1.Reflection.FileDescriptorsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.reflection.v1.Reflection.FileDescriptorsRequest();
    }

    public static cosmos.reflection.v1.Reflection.FileDescriptorsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileDescriptorsRequest>
        PARSER = new com.google.protobuf.AbstractParser<FileDescriptorsRequest>() {
      @java.lang.Override
      public FileDescriptorsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileDescriptorsRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileDescriptorsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileDescriptorsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cosmos.reflection.v1.Reflection.FileDescriptorsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FileDescriptorsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.reflection.v1.FileDescriptorsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * files is the file descriptors.
     * </pre>
     *
     * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
     */
    java.util.List<com.google.protobuf.DescriptorProtos.FileDescriptorProto> 
        getFilesList();
    /**
     * <pre>
     * files is the file descriptors.
     * </pre>
     *
     * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorProto getFiles(int index);
    /**
     * <pre>
     * files is the file descriptors.
     * </pre>
     *
     * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
     */
    int getFilesCount();
    /**
     * <pre>
     * files is the file descriptors.
     * </pre>
     *
     * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
     */
    java.util.List<? extends com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder> 
        getFilesOrBuilderList();
    /**
     * <pre>
     * files is the file descriptors.
     * </pre>
     *
     * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
     */
    com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder getFilesOrBuilder(
        int index);
  }
  /**
   * <pre>
   * FileDescriptorsResponse is the Query/FileDescriptors response type.
   * </pre>
   *
   * Protobuf type {@code cosmos.reflection.v1.FileDescriptorsResponse}
   */
  public static final class FileDescriptorsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.reflection.v1.FileDescriptorsResponse)
      FileDescriptorsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FileDescriptorsResponse.newBuilder() to construct.
    private FileDescriptorsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FileDescriptorsResponse() {
      files_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FileDescriptorsResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FileDescriptorsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                files_ = new java.util.ArrayList<com.google.protobuf.DescriptorProtos.FileDescriptorProto>();
                mutable_bitField0_ |= 0x00000001;
              }
              files_.add(
                  input.readMessage(com.google.protobuf.DescriptorProtos.FileDescriptorProto.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          files_ = java.util.Collections.unmodifiableList(files_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.reflection.v1.Reflection.internal_static_cosmos_reflection_v1_FileDescriptorsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.reflection.v1.Reflection.internal_static_cosmos_reflection_v1_FileDescriptorsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.reflection.v1.Reflection.FileDescriptorsResponse.class, cosmos.reflection.v1.Reflection.FileDescriptorsResponse.Builder.class);
    }

    public static final int FILES_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.DescriptorProtos.FileDescriptorProto> files_;
    /**
     * <pre>
     * files is the file descriptors.
     * </pre>
     *
     * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.DescriptorProtos.FileDescriptorProto> getFilesList() {
      return files_;
    }
    /**
     * <pre>
     * files is the file descriptors.
     * </pre>
     *
     * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder> 
        getFilesOrBuilderList() {
      return files_;
    }
    /**
     * <pre>
     * files is the file descriptors.
     * </pre>
     *
     * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
     */
    @java.lang.Override
    public int getFilesCount() {
      return files_.size();
    }
    /**
     * <pre>
     * files is the file descriptors.
     * </pre>
     *
     * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DescriptorProtos.FileDescriptorProto getFiles(int index) {
      return files_.get(index);
    }
    /**
     * <pre>
     * files is the file descriptors.
     * </pre>
     *
     * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder getFilesOrBuilder(
        int index) {
      return files_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getFilesCount(); i++) {
        if (!getFiles(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < files_.size(); i++) {
        output.writeMessage(1, files_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < files_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, files_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.reflection.v1.Reflection.FileDescriptorsResponse)) {
        return super.equals(obj);
      }
      cosmos.reflection.v1.Reflection.FileDescriptorsResponse other = (cosmos.reflection.v1.Reflection.FileDescriptorsResponse) obj;

      if (!getFilesList()
          .equals(other.getFilesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getFilesCount() > 0) {
        hash = (37 * hash) + FILES_FIELD_NUMBER;
        hash = (53 * hash) + getFilesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.reflection.v1.Reflection.FileDescriptorsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * FileDescriptorsResponse is the Query/FileDescriptors response type.
     * </pre>
     *
     * Protobuf type {@code cosmos.reflection.v1.FileDescriptorsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.reflection.v1.FileDescriptorsResponse)
        cosmos.reflection.v1.Reflection.FileDescriptorsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.reflection.v1.Reflection.internal_static_cosmos_reflection_v1_FileDescriptorsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.reflection.v1.Reflection.internal_static_cosmos_reflection_v1_FileDescriptorsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.reflection.v1.Reflection.FileDescriptorsResponse.class, cosmos.reflection.v1.Reflection.FileDescriptorsResponse.Builder.class);
      }

      // Construct using cosmos.reflection.v1.Reflection.FileDescriptorsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFilesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (filesBuilder_ == null) {
          files_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          filesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.reflection.v1.Reflection.internal_static_cosmos_reflection_v1_FileDescriptorsResponse_descriptor;
      }

      @java.lang.Override
      public cosmos.reflection.v1.Reflection.FileDescriptorsResponse getDefaultInstanceForType() {
        return cosmos.reflection.v1.Reflection.FileDescriptorsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cosmos.reflection.v1.Reflection.FileDescriptorsResponse build() {
        cosmos.reflection.v1.Reflection.FileDescriptorsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cosmos.reflection.v1.Reflection.FileDescriptorsResponse buildPartial() {
        cosmos.reflection.v1.Reflection.FileDescriptorsResponse result = new cosmos.reflection.v1.Reflection.FileDescriptorsResponse(this);
        int from_bitField0_ = bitField0_;
        if (filesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            files_ = java.util.Collections.unmodifiableList(files_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.files_ = files_;
        } else {
          result.files_ = filesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.reflection.v1.Reflection.FileDescriptorsResponse) {
          return mergeFrom((cosmos.reflection.v1.Reflection.FileDescriptorsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.reflection.v1.Reflection.FileDescriptorsResponse other) {
        if (other == cosmos.reflection.v1.Reflection.FileDescriptorsResponse.getDefaultInstance()) return this;
        if (filesBuilder_ == null) {
          if (!other.files_.isEmpty()) {
            if (files_.isEmpty()) {
              files_ = other.files_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureFilesIsMutable();
              files_.addAll(other.files_);
            }
            onChanged();
          }
        } else {
          if (!other.files_.isEmpty()) {
            if (filesBuilder_.isEmpty()) {
              filesBuilder_.dispose();
              filesBuilder_ = null;
              files_ = other.files_;
              bitField0_ = (bitField0_ & ~0x00000001);
              filesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFilesFieldBuilder() : null;
            } else {
              filesBuilder_.addAllMessages(other.files_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getFilesCount(); i++) {
          if (!getFiles(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.reflection.v1.Reflection.FileDescriptorsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.reflection.v1.Reflection.FileDescriptorsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.DescriptorProtos.FileDescriptorProto> files_ =
        java.util.Collections.emptyList();
      private void ensureFilesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          files_ = new java.util.ArrayList<com.google.protobuf.DescriptorProtos.FileDescriptorProto>(files_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorProto, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder> filesBuilder_;

      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public java.util.List<com.google.protobuf.DescriptorProtos.FileDescriptorProto> getFilesList() {
        if (filesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(files_);
        } else {
          return filesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public int getFilesCount() {
        if (filesBuilder_ == null) {
          return files_.size();
        } else {
          return filesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorProto getFiles(int index) {
        if (filesBuilder_ == null) {
          return files_.get(index);
        } else {
          return filesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public Builder setFiles(
          int index, com.google.protobuf.DescriptorProtos.FileDescriptorProto value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.set(index, value);
          onChanged();
        } else {
          filesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public Builder setFiles(
          int index, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.set(index, builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public Builder addFiles(com.google.protobuf.DescriptorProtos.FileDescriptorProto value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.add(value);
          onChanged();
        } else {
          filesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public Builder addFiles(
          int index, com.google.protobuf.DescriptorProtos.FileDescriptorProto value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.add(index, value);
          onChanged();
        } else {
          filesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public Builder addFiles(
          com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.add(builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public Builder addFiles(
          int index, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.add(index, builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public Builder addAllFiles(
          java.lang.Iterable<? extends com.google.protobuf.DescriptorProtos.FileDescriptorProto> values) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, files_);
          onChanged();
        } else {
          filesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public Builder clearFiles() {
        if (filesBuilder_ == null) {
          files_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          filesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public Builder removeFiles(int index) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.remove(index);
          onChanged();
        } else {
          filesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder getFilesBuilder(
          int index) {
        return getFilesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder getFilesOrBuilder(
          int index) {
        if (filesBuilder_ == null) {
          return files_.get(index);  } else {
          return filesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public java.util.List<? extends com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder> 
           getFilesOrBuilderList() {
        if (filesBuilder_ != null) {
          return filesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(files_);
        }
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder addFilesBuilder() {
        return getFilesFieldBuilder().addBuilder(
            com.google.protobuf.DescriptorProtos.FileDescriptorProto.getDefaultInstance());
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder addFilesBuilder(
          int index) {
        return getFilesFieldBuilder().addBuilder(
            index, com.google.protobuf.DescriptorProtos.FileDescriptorProto.getDefaultInstance());
      }
      /**
       * <pre>
       * files is the file descriptors.
       * </pre>
       *
       * <code>repeated .google.protobuf.FileDescriptorProto files = 1;</code>
       */
      public java.util.List<com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder> 
           getFilesBuilderList() {
        return getFilesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.DescriptorProtos.FileDescriptorProto, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder> 
          getFilesFieldBuilder() {
        if (filesBuilder_ == null) {
          filesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.DescriptorProtos.FileDescriptorProto, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder>(
                  files_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          files_ = null;
        }
        return filesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.reflection.v1.FileDescriptorsResponse)
    }

    // @@protoc_insertion_point(class_scope:cosmos.reflection.v1.FileDescriptorsResponse)
    private static final cosmos.reflection.v1.Reflection.FileDescriptorsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.reflection.v1.Reflection.FileDescriptorsResponse();
    }

    public static cosmos.reflection.v1.Reflection.FileDescriptorsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FileDescriptorsResponse>
        PARSER = new com.google.protobuf.AbstractParser<FileDescriptorsResponse>() {
      @java.lang.Override
      public FileDescriptorsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FileDescriptorsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FileDescriptorsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FileDescriptorsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cosmos.reflection.v1.Reflection.FileDescriptorsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_reflection_v1_FileDescriptorsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_reflection_v1_FileDescriptorsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_reflection_v1_FileDescriptorsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_reflection_v1_FileDescriptorsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%cosmos/reflection/v1/reflection.proto\022" +
      "\024cosmos.reflection.v1\032 google/protobuf/d" +
      "escriptor.proto\032\033cosmos/query/v1/query.p" +
      "roto\"\030\n\026FileDescriptorsRequest\"N\n\027FileDe" +
      "scriptorsResponse\0223\n\005files\030\001 \003(\0132$.googl" +
      "e.protobuf.FileDescriptorProto2\212\001\n\021Refle" +
      "ctionService\022u\n\017FileDescriptors\022,.cosmos" +
      ".reflection.v1.FileDescriptorsRequest\032-." +
      "cosmos.reflection.v1.FileDescriptorsResp" +
      "onse\"\005\210\347\260*\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
          cosmos.query.v1.Query.getDescriptor(),
        });
    internal_static_cosmos_reflection_v1_FileDescriptorsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cosmos_reflection_v1_FileDescriptorsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_reflection_v1_FileDescriptorsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_cosmos_reflection_v1_FileDescriptorsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cosmos_reflection_v1_FileDescriptorsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_reflection_v1_FileDescriptorsResponse_descriptor,
        new java.lang.String[] { "Files", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(cosmos.query.v1.Query.moduleQuerySafe);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.DescriptorProtos.getDescriptor();
    cosmos.query.v1.Query.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
