// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cosmos/slashing/v1beta1/tx.proto

package cosmos.slashing.v1beta1;

public final class Tx {
  private Tx() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MsgUnjailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.slashing.v1beta1.MsgUnjail)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string validator_addr = 1 [(.gogoproto.jsontag) = "address", (.cosmos_proto.scalar) = "cosmos.AddressString", (.amino.field_name) = "address", (.amino.dont_omitempty) = true];</code>
     * @return The validatorAddr.
     */
    java.lang.String getValidatorAddr();
    /**
     * <code>string validator_addr = 1 [(.gogoproto.jsontag) = "address", (.cosmos_proto.scalar) = "cosmos.AddressString", (.amino.field_name) = "address", (.amino.dont_omitempty) = true];</code>
     * @return The bytes for validatorAddr.
     */
    com.google.protobuf.ByteString
        getValidatorAddrBytes();
  }
  /**
   * <pre>
   * MsgUnjail defines the Msg/Unjail request type
   * </pre>
   *
   * Protobuf type {@code cosmos.slashing.v1beta1.MsgUnjail}
   */
  public static final class MsgUnjail extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.slashing.v1beta1.MsgUnjail)
      MsgUnjailOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgUnjail.newBuilder() to construct.
    private MsgUnjail(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgUnjail() {
      validatorAddr_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgUnjail();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgUnjail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              validatorAddr_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUnjail_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUnjail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.slashing.v1beta1.Tx.MsgUnjail.class, cosmos.slashing.v1beta1.Tx.MsgUnjail.Builder.class);
    }

    public static final int VALIDATOR_ADDR_FIELD_NUMBER = 1;
    private volatile java.lang.Object validatorAddr_;
    /**
     * <code>string validator_addr = 1 [(.gogoproto.jsontag) = "address", (.cosmos_proto.scalar) = "cosmos.AddressString", (.amino.field_name) = "address", (.amino.dont_omitempty) = true];</code>
     * @return The validatorAddr.
     */
    @java.lang.Override
    public java.lang.String getValidatorAddr() {
      java.lang.Object ref = validatorAddr_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        validatorAddr_ = s;
        return s;
      }
    }
    /**
     * <code>string validator_addr = 1 [(.gogoproto.jsontag) = "address", (.cosmos_proto.scalar) = "cosmos.AddressString", (.amino.field_name) = "address", (.amino.dont_omitempty) = true];</code>
     * @return The bytes for validatorAddr.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getValidatorAddrBytes() {
      java.lang.Object ref = validatorAddr_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        validatorAddr_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(validatorAddr_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, validatorAddr_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(validatorAddr_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, validatorAddr_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.slashing.v1beta1.Tx.MsgUnjail)) {
        return super.equals(obj);
      }
      cosmos.slashing.v1beta1.Tx.MsgUnjail other = (cosmos.slashing.v1beta1.Tx.MsgUnjail) obj;

      if (!getValidatorAddr()
          .equals(other.getValidatorAddr())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALIDATOR_ADDR_FIELD_NUMBER;
      hash = (53 * hash) + getValidatorAddr().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.slashing.v1beta1.Tx.MsgUnjail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.slashing.v1beta1.Tx.MsgUnjail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MsgUnjail defines the Msg/Unjail request type
     * </pre>
     *
     * Protobuf type {@code cosmos.slashing.v1beta1.MsgUnjail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.slashing.v1beta1.MsgUnjail)
        cosmos.slashing.v1beta1.Tx.MsgUnjailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUnjail_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUnjail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.slashing.v1beta1.Tx.MsgUnjail.class, cosmos.slashing.v1beta1.Tx.MsgUnjail.Builder.class);
      }

      // Construct using cosmos.slashing.v1beta1.Tx.MsgUnjail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        validatorAddr_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUnjail_descriptor;
      }

      @java.lang.Override
      public cosmos.slashing.v1beta1.Tx.MsgUnjail getDefaultInstanceForType() {
        return cosmos.slashing.v1beta1.Tx.MsgUnjail.getDefaultInstance();
      }

      @java.lang.Override
      public cosmos.slashing.v1beta1.Tx.MsgUnjail build() {
        cosmos.slashing.v1beta1.Tx.MsgUnjail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cosmos.slashing.v1beta1.Tx.MsgUnjail buildPartial() {
        cosmos.slashing.v1beta1.Tx.MsgUnjail result = new cosmos.slashing.v1beta1.Tx.MsgUnjail(this);
        result.validatorAddr_ = validatorAddr_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.slashing.v1beta1.Tx.MsgUnjail) {
          return mergeFrom((cosmos.slashing.v1beta1.Tx.MsgUnjail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.slashing.v1beta1.Tx.MsgUnjail other) {
        if (other == cosmos.slashing.v1beta1.Tx.MsgUnjail.getDefaultInstance()) return this;
        if (!other.getValidatorAddr().isEmpty()) {
          validatorAddr_ = other.validatorAddr_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.slashing.v1beta1.Tx.MsgUnjail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.slashing.v1beta1.Tx.MsgUnjail) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object validatorAddr_ = "";
      /**
       * <code>string validator_addr = 1 [(.gogoproto.jsontag) = "address", (.cosmos_proto.scalar) = "cosmos.AddressString", (.amino.field_name) = "address", (.amino.dont_omitempty) = true];</code>
       * @return The validatorAddr.
       */
      public java.lang.String getValidatorAddr() {
        java.lang.Object ref = validatorAddr_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          validatorAddr_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string validator_addr = 1 [(.gogoproto.jsontag) = "address", (.cosmos_proto.scalar) = "cosmos.AddressString", (.amino.field_name) = "address", (.amino.dont_omitempty) = true];</code>
       * @return The bytes for validatorAddr.
       */
      public com.google.protobuf.ByteString
          getValidatorAddrBytes() {
        java.lang.Object ref = validatorAddr_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          validatorAddr_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string validator_addr = 1 [(.gogoproto.jsontag) = "address", (.cosmos_proto.scalar) = "cosmos.AddressString", (.amino.field_name) = "address", (.amino.dont_omitempty) = true];</code>
       * @param value The validatorAddr to set.
       * @return This builder for chaining.
       */
      public Builder setValidatorAddr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        validatorAddr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string validator_addr = 1 [(.gogoproto.jsontag) = "address", (.cosmos_proto.scalar) = "cosmos.AddressString", (.amino.field_name) = "address", (.amino.dont_omitempty) = true];</code>
       * @return This builder for chaining.
       */
      public Builder clearValidatorAddr() {
        
        validatorAddr_ = getDefaultInstance().getValidatorAddr();
        onChanged();
        return this;
      }
      /**
       * <code>string validator_addr = 1 [(.gogoproto.jsontag) = "address", (.cosmos_proto.scalar) = "cosmos.AddressString", (.amino.field_name) = "address", (.amino.dont_omitempty) = true];</code>
       * @param value The bytes for validatorAddr to set.
       * @return This builder for chaining.
       */
      public Builder setValidatorAddrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        validatorAddr_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.slashing.v1beta1.MsgUnjail)
    }

    // @@protoc_insertion_point(class_scope:cosmos.slashing.v1beta1.MsgUnjail)
    private static final cosmos.slashing.v1beta1.Tx.MsgUnjail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.slashing.v1beta1.Tx.MsgUnjail();
    }

    public static cosmos.slashing.v1beta1.Tx.MsgUnjail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgUnjail>
        PARSER = new com.google.protobuf.AbstractParser<MsgUnjail>() {
      @java.lang.Override
      public MsgUnjail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgUnjail(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgUnjail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgUnjail> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cosmos.slashing.v1beta1.Tx.MsgUnjail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgUnjailResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.slashing.v1beta1.MsgUnjailResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * MsgUnjailResponse defines the Msg/Unjail response type
   * </pre>
   *
   * Protobuf type {@code cosmos.slashing.v1beta1.MsgUnjailResponse}
   */
  public static final class MsgUnjailResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.slashing.v1beta1.MsgUnjailResponse)
      MsgUnjailResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgUnjailResponse.newBuilder() to construct.
    private MsgUnjailResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgUnjailResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgUnjailResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgUnjailResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUnjailResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUnjailResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.slashing.v1beta1.Tx.MsgUnjailResponse.class, cosmos.slashing.v1beta1.Tx.MsgUnjailResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.slashing.v1beta1.Tx.MsgUnjailResponse)) {
        return super.equals(obj);
      }
      cosmos.slashing.v1beta1.Tx.MsgUnjailResponse other = (cosmos.slashing.v1beta1.Tx.MsgUnjailResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.slashing.v1beta1.Tx.MsgUnjailResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MsgUnjailResponse defines the Msg/Unjail response type
     * </pre>
     *
     * Protobuf type {@code cosmos.slashing.v1beta1.MsgUnjailResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.slashing.v1beta1.MsgUnjailResponse)
        cosmos.slashing.v1beta1.Tx.MsgUnjailResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUnjailResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUnjailResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.slashing.v1beta1.Tx.MsgUnjailResponse.class, cosmos.slashing.v1beta1.Tx.MsgUnjailResponse.Builder.class);
      }

      // Construct using cosmos.slashing.v1beta1.Tx.MsgUnjailResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUnjailResponse_descriptor;
      }

      @java.lang.Override
      public cosmos.slashing.v1beta1.Tx.MsgUnjailResponse getDefaultInstanceForType() {
        return cosmos.slashing.v1beta1.Tx.MsgUnjailResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cosmos.slashing.v1beta1.Tx.MsgUnjailResponse build() {
        cosmos.slashing.v1beta1.Tx.MsgUnjailResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cosmos.slashing.v1beta1.Tx.MsgUnjailResponse buildPartial() {
        cosmos.slashing.v1beta1.Tx.MsgUnjailResponse result = new cosmos.slashing.v1beta1.Tx.MsgUnjailResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.slashing.v1beta1.Tx.MsgUnjailResponse) {
          return mergeFrom((cosmos.slashing.v1beta1.Tx.MsgUnjailResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.slashing.v1beta1.Tx.MsgUnjailResponse other) {
        if (other == cosmos.slashing.v1beta1.Tx.MsgUnjailResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.slashing.v1beta1.Tx.MsgUnjailResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.slashing.v1beta1.Tx.MsgUnjailResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.slashing.v1beta1.MsgUnjailResponse)
    }

    // @@protoc_insertion_point(class_scope:cosmos.slashing.v1beta1.MsgUnjailResponse)
    private static final cosmos.slashing.v1beta1.Tx.MsgUnjailResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.slashing.v1beta1.Tx.MsgUnjailResponse();
    }

    public static cosmos.slashing.v1beta1.Tx.MsgUnjailResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgUnjailResponse>
        PARSER = new com.google.protobuf.AbstractParser<MsgUnjailResponse>() {
      @java.lang.Override
      public MsgUnjailResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgUnjailResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgUnjailResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgUnjailResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cosmos.slashing.v1beta1.Tx.MsgUnjailResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgUpdateParamsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.slashing.v1beta1.MsgUpdateParams)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * authority is the address that controls the module (defaults to x/gov unless overwritten).
     * </pre>
     *
     * <code>string authority = 1 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return The authority.
     */
    java.lang.String getAuthority();
    /**
     * <pre>
     * authority is the address that controls the module (defaults to x/gov unless overwritten).
     * </pre>
     *
     * <code>string authority = 1 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return The bytes for authority.
     */
    com.google.protobuf.ByteString
        getAuthorityBytes();

    /**
     * <pre>
     * params defines the x/slashing parameters to update.
     * NOTE: All parameters must be supplied.
     * </pre>
     *
     * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     * @return Whether the params field is set.
     */
    boolean hasParams();
    /**
     * <pre>
     * params defines the x/slashing parameters to update.
     * NOTE: All parameters must be supplied.
     * </pre>
     *
     * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     * @return The params.
     */
    cosmos.slashing.v1beta1.Slashing.Params getParams();
    /**
     * <pre>
     * params defines the x/slashing parameters to update.
     * NOTE: All parameters must be supplied.
     * </pre>
     *
     * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     */
    cosmos.slashing.v1beta1.Slashing.ParamsOrBuilder getParamsOrBuilder();
  }
  /**
   * <pre>
   * MsgUpdateParams is the Msg/UpdateParams request type.
   * Since: cosmos-sdk 0.47
   * </pre>
   *
   * Protobuf type {@code cosmos.slashing.v1beta1.MsgUpdateParams}
   */
  public static final class MsgUpdateParams extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.slashing.v1beta1.MsgUpdateParams)
      MsgUpdateParamsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgUpdateParams.newBuilder() to construct.
    private MsgUpdateParams(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgUpdateParams() {
      authority_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgUpdateParams();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgUpdateParams(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              authority_ = s;
              break;
            }
            case 18: {
              cosmos.slashing.v1beta1.Slashing.Params.Builder subBuilder = null;
              if (params_ != null) {
                subBuilder = params_.toBuilder();
              }
              params_ = input.readMessage(cosmos.slashing.v1beta1.Slashing.Params.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(params_);
                params_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUpdateParams_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUpdateParams_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.slashing.v1beta1.Tx.MsgUpdateParams.class, cosmos.slashing.v1beta1.Tx.MsgUpdateParams.Builder.class);
    }

    public static final int AUTHORITY_FIELD_NUMBER = 1;
    private volatile java.lang.Object authority_;
    /**
     * <pre>
     * authority is the address that controls the module (defaults to x/gov unless overwritten).
     * </pre>
     *
     * <code>string authority = 1 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return The authority.
     */
    @java.lang.Override
    public java.lang.String getAuthority() {
      java.lang.Object ref = authority_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authority_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * authority is the address that controls the module (defaults to x/gov unless overwritten).
     * </pre>
     *
     * <code>string authority = 1 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
     * @return The bytes for authority.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAuthorityBytes() {
      java.lang.Object ref = authority_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authority_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMS_FIELD_NUMBER = 2;
    private cosmos.slashing.v1beta1.Slashing.Params params_;
    /**
     * <pre>
     * params defines the x/slashing parameters to update.
     * NOTE: All parameters must be supplied.
     * </pre>
     *
     * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     * @return Whether the params field is set.
     */
    @java.lang.Override
    public boolean hasParams() {
      return params_ != null;
    }
    /**
     * <pre>
     * params defines the x/slashing parameters to update.
     * NOTE: All parameters must be supplied.
     * </pre>
     *
     * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     * @return The params.
     */
    @java.lang.Override
    public cosmos.slashing.v1beta1.Slashing.Params getParams() {
      return params_ == null ? cosmos.slashing.v1beta1.Slashing.Params.getDefaultInstance() : params_;
    }
    /**
     * <pre>
     * params defines the x/slashing parameters to update.
     * NOTE: All parameters must be supplied.
     * </pre>
     *
     * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
     */
    @java.lang.Override
    public cosmos.slashing.v1beta1.Slashing.ParamsOrBuilder getParamsOrBuilder() {
      return getParams();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authority_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, authority_);
      }
      if (params_ != null) {
        output.writeMessage(2, getParams());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(authority_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, authority_);
      }
      if (params_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getParams());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.slashing.v1beta1.Tx.MsgUpdateParams)) {
        return super.equals(obj);
      }
      cosmos.slashing.v1beta1.Tx.MsgUpdateParams other = (cosmos.slashing.v1beta1.Tx.MsgUpdateParams) obj;

      if (!getAuthority()
          .equals(other.getAuthority())) return false;
      if (hasParams() != other.hasParams()) return false;
      if (hasParams()) {
        if (!getParams()
            .equals(other.getParams())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUTHORITY_FIELD_NUMBER;
      hash = (53 * hash) + getAuthority().hashCode();
      if (hasParams()) {
        hash = (37 * hash) + PARAMS_FIELD_NUMBER;
        hash = (53 * hash) + getParams().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.slashing.v1beta1.Tx.MsgUpdateParams prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MsgUpdateParams is the Msg/UpdateParams request type.
     * Since: cosmos-sdk 0.47
     * </pre>
     *
     * Protobuf type {@code cosmos.slashing.v1beta1.MsgUpdateParams}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.slashing.v1beta1.MsgUpdateParams)
        cosmos.slashing.v1beta1.Tx.MsgUpdateParamsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUpdateParams_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUpdateParams_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.slashing.v1beta1.Tx.MsgUpdateParams.class, cosmos.slashing.v1beta1.Tx.MsgUpdateParams.Builder.class);
      }

      // Construct using cosmos.slashing.v1beta1.Tx.MsgUpdateParams.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        authority_ = "";

        if (paramsBuilder_ == null) {
          params_ = null;
        } else {
          params_ = null;
          paramsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUpdateParams_descriptor;
      }

      @java.lang.Override
      public cosmos.slashing.v1beta1.Tx.MsgUpdateParams getDefaultInstanceForType() {
        return cosmos.slashing.v1beta1.Tx.MsgUpdateParams.getDefaultInstance();
      }

      @java.lang.Override
      public cosmos.slashing.v1beta1.Tx.MsgUpdateParams build() {
        cosmos.slashing.v1beta1.Tx.MsgUpdateParams result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cosmos.slashing.v1beta1.Tx.MsgUpdateParams buildPartial() {
        cosmos.slashing.v1beta1.Tx.MsgUpdateParams result = new cosmos.slashing.v1beta1.Tx.MsgUpdateParams(this);
        result.authority_ = authority_;
        if (paramsBuilder_ == null) {
          result.params_ = params_;
        } else {
          result.params_ = paramsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.slashing.v1beta1.Tx.MsgUpdateParams) {
          return mergeFrom((cosmos.slashing.v1beta1.Tx.MsgUpdateParams)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.slashing.v1beta1.Tx.MsgUpdateParams other) {
        if (other == cosmos.slashing.v1beta1.Tx.MsgUpdateParams.getDefaultInstance()) return this;
        if (!other.getAuthority().isEmpty()) {
          authority_ = other.authority_;
          onChanged();
        }
        if (other.hasParams()) {
          mergeParams(other.getParams());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.slashing.v1beta1.Tx.MsgUpdateParams parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.slashing.v1beta1.Tx.MsgUpdateParams) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object authority_ = "";
      /**
       * <pre>
       * authority is the address that controls the module (defaults to x/gov unless overwritten).
       * </pre>
       *
       * <code>string authority = 1 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
       * @return The authority.
       */
      public java.lang.String getAuthority() {
        java.lang.Object ref = authority_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authority_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * authority is the address that controls the module (defaults to x/gov unless overwritten).
       * </pre>
       *
       * <code>string authority = 1 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
       * @return The bytes for authority.
       */
      public com.google.protobuf.ByteString
          getAuthorityBytes() {
        java.lang.Object ref = authority_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authority_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * authority is the address that controls the module (defaults to x/gov unless overwritten).
       * </pre>
       *
       * <code>string authority = 1 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
       * @param value The authority to set.
       * @return This builder for chaining.
       */
      public Builder setAuthority(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authority_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * authority is the address that controls the module (defaults to x/gov unless overwritten).
       * </pre>
       *
       * <code>string authority = 1 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthority() {
        
        authority_ = getDefaultInstance().getAuthority();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * authority is the address that controls the module (defaults to x/gov unless overwritten).
       * </pre>
       *
       * <code>string authority = 1 [(.cosmos_proto.scalar) = "cosmos.AddressString"];</code>
       * @param value The bytes for authority to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authority_ = value;
        onChanged();
        return this;
      }

      private cosmos.slashing.v1beta1.Slashing.Params params_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.slashing.v1beta1.Slashing.Params, cosmos.slashing.v1beta1.Slashing.Params.Builder, cosmos.slashing.v1beta1.Slashing.ParamsOrBuilder> paramsBuilder_;
      /**
       * <pre>
       * params defines the x/slashing parameters to update.
       * NOTE: All parameters must be supplied.
       * </pre>
       *
       * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       * @return Whether the params field is set.
       */
      public boolean hasParams() {
        return paramsBuilder_ != null || params_ != null;
      }
      /**
       * <pre>
       * params defines the x/slashing parameters to update.
       * NOTE: All parameters must be supplied.
       * </pre>
       *
       * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       * @return The params.
       */
      public cosmos.slashing.v1beta1.Slashing.Params getParams() {
        if (paramsBuilder_ == null) {
          return params_ == null ? cosmos.slashing.v1beta1.Slashing.Params.getDefaultInstance() : params_;
        } else {
          return paramsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * params defines the x/slashing parameters to update.
       * NOTE: All parameters must be supplied.
       * </pre>
       *
       * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public Builder setParams(cosmos.slashing.v1beta1.Slashing.Params value) {
        if (paramsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          params_ = value;
          onChanged();
        } else {
          paramsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * params defines the x/slashing parameters to update.
       * NOTE: All parameters must be supplied.
       * </pre>
       *
       * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public Builder setParams(
          cosmos.slashing.v1beta1.Slashing.Params.Builder builderForValue) {
        if (paramsBuilder_ == null) {
          params_ = builderForValue.build();
          onChanged();
        } else {
          paramsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * params defines the x/slashing parameters to update.
       * NOTE: All parameters must be supplied.
       * </pre>
       *
       * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public Builder mergeParams(cosmos.slashing.v1beta1.Slashing.Params value) {
        if (paramsBuilder_ == null) {
          if (params_ != null) {
            params_ =
              cosmos.slashing.v1beta1.Slashing.Params.newBuilder(params_).mergeFrom(value).buildPartial();
          } else {
            params_ = value;
          }
          onChanged();
        } else {
          paramsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * params defines the x/slashing parameters to update.
       * NOTE: All parameters must be supplied.
       * </pre>
       *
       * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public Builder clearParams() {
        if (paramsBuilder_ == null) {
          params_ = null;
          onChanged();
        } else {
          params_ = null;
          paramsBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * params defines the x/slashing parameters to update.
       * NOTE: All parameters must be supplied.
       * </pre>
       *
       * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public cosmos.slashing.v1beta1.Slashing.Params.Builder getParamsBuilder() {
        
        onChanged();
        return getParamsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * params defines the x/slashing parameters to update.
       * NOTE: All parameters must be supplied.
       * </pre>
       *
       * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      public cosmos.slashing.v1beta1.Slashing.ParamsOrBuilder getParamsOrBuilder() {
        if (paramsBuilder_ != null) {
          return paramsBuilder_.getMessageOrBuilder();
        } else {
          return params_ == null ?
              cosmos.slashing.v1beta1.Slashing.Params.getDefaultInstance() : params_;
        }
      }
      /**
       * <pre>
       * params defines the x/slashing parameters to update.
       * NOTE: All parameters must be supplied.
       * </pre>
       *
       * <code>.cosmos.slashing.v1beta1.Params params = 2 [(.gogoproto.nullable) = false, (.amino.dont_omitempty) = true];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cosmos.slashing.v1beta1.Slashing.Params, cosmos.slashing.v1beta1.Slashing.Params.Builder, cosmos.slashing.v1beta1.Slashing.ParamsOrBuilder> 
          getParamsFieldBuilder() {
        if (paramsBuilder_ == null) {
          paramsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cosmos.slashing.v1beta1.Slashing.Params, cosmos.slashing.v1beta1.Slashing.Params.Builder, cosmos.slashing.v1beta1.Slashing.ParamsOrBuilder>(
                  getParams(),
                  getParentForChildren(),
                  isClean());
          params_ = null;
        }
        return paramsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.slashing.v1beta1.MsgUpdateParams)
    }

    // @@protoc_insertion_point(class_scope:cosmos.slashing.v1beta1.MsgUpdateParams)
    private static final cosmos.slashing.v1beta1.Tx.MsgUpdateParams DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.slashing.v1beta1.Tx.MsgUpdateParams();
    }

    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParams getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgUpdateParams>
        PARSER = new com.google.protobuf.AbstractParser<MsgUpdateParams>() {
      @java.lang.Override
      public MsgUpdateParams parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgUpdateParams(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgUpdateParams> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgUpdateParams> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cosmos.slashing.v1beta1.Tx.MsgUpdateParams getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MsgUpdateParamsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cosmos.slashing.v1beta1.MsgUpdateParamsResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * <pre>
   * MsgUpdateParamsResponse defines the response structure for executing a
   * MsgUpdateParams message.
   * Since: cosmos-sdk 0.47
   * </pre>
   *
   * Protobuf type {@code cosmos.slashing.v1beta1.MsgUpdateParamsResponse}
   */
  public static final class MsgUpdateParamsResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cosmos.slashing.v1beta1.MsgUpdateParamsResponse)
      MsgUpdateParamsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MsgUpdateParamsResponse.newBuilder() to construct.
    private MsgUpdateParamsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MsgUpdateParamsResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MsgUpdateParamsResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MsgUpdateParamsResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUpdateParamsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUpdateParamsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse.class, cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse)) {
        return super.equals(obj);
      }
      cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse other = (cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * MsgUpdateParamsResponse defines the response structure for executing a
     * MsgUpdateParams message.
     * Since: cosmos-sdk 0.47
     * </pre>
     *
     * Protobuf type {@code cosmos.slashing.v1beta1.MsgUpdateParamsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cosmos.slashing.v1beta1.MsgUpdateParamsResponse)
        cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUpdateParamsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUpdateParamsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse.class, cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse.Builder.class);
      }

      // Construct using cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cosmos.slashing.v1beta1.Tx.internal_static_cosmos_slashing_v1beta1_MsgUpdateParamsResponse_descriptor;
      }

      @java.lang.Override
      public cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse getDefaultInstanceForType() {
        return cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse build() {
        cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse buildPartial() {
        cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse result = new cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse) {
          return mergeFrom((cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse other) {
        if (other == cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cosmos.slashing.v1beta1.MsgUpdateParamsResponse)
    }

    // @@protoc_insertion_point(class_scope:cosmos.slashing.v1beta1.MsgUpdateParamsResponse)
    private static final cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse();
    }

    public static cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MsgUpdateParamsResponse>
        PARSER = new com.google.protobuf.AbstractParser<MsgUpdateParamsResponse>() {
      @java.lang.Override
      public MsgUpdateParamsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgUpdateParamsResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MsgUpdateParamsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MsgUpdateParamsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cosmos.slashing.v1beta1.Tx.MsgUpdateParamsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_slashing_v1beta1_MsgUnjail_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_slashing_v1beta1_MsgUnjail_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_slashing_v1beta1_MsgUnjailResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_slashing_v1beta1_MsgUnjailResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_slashing_v1beta1_MsgUpdateParams_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_slashing_v1beta1_MsgUpdateParams_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cosmos_slashing_v1beta1_MsgUpdateParamsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cosmos_slashing_v1beta1_MsgUpdateParamsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n cosmos/slashing/v1beta1/tx.proto\022\027cosm" +
      "os.slashing.v1beta1\032\024gogoproto/gogo.prot" +
      "o\032&cosmos/slashing/v1beta1/slashing.prot" +
      "o\032\031cosmos_proto/cosmos.proto\032\027cosmos/msg" +
      "/v1/msg.proto\032\021amino/amino.proto\"\213\001\n\tMsg" +
      "Unjail\022L\n\016validator_addr\030\001 \001(\tB4\322\264-\024cosm" +
      "os.AddressString\352\336\037\007address\242\347\260*\007address\250" +
      "\347\260*\001:0\202\347\260*\016validator_addr\212\347\260*\024cosmos-sdk" +
      "/MsgUnjail\210\240\037\000\"\023\n\021MsgUnjailResponse\"\264\001\n\017" +
      "MsgUpdateParams\022+\n\tauthority\030\001 \001(\tB\030\322\264-\024" +
      "cosmos.AddressString\022:\n\006params\030\002 \001(\0132\037.c" +
      "osmos.slashing.v1beta1.ParamsB\t\310\336\037\000\250\347\260*\001" +
      ":8\202\347\260*\tauthority\212\347\260*%cosmos-sdk/x/slashi" +
      "ng/MsgUpdateParams\"\031\n\027MsgUpdateParamsRes" +
      "ponse2\322\001\n\003Msg\022X\n\006Unjail\022\".cosmos.slashin" +
      "g.v1beta1.MsgUnjail\032*.cosmos.slashing.v1" +
      "beta1.MsgUnjailResponse\022j\n\014UpdateParams\022" +
      "(.cosmos.slashing.v1beta1.MsgUpdateParam" +
      "s\0320.cosmos.slashing.v1beta1.MsgUpdatePar" +
      "amsResponse\032\005\200\347\260*\001B3Z-github.com/cosmos/" +
      "cosmos-sdk/x/slashing/types\250\342\036\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.GoGoProtos.getDescriptor(),
          cosmos.slashing.v1beta1.Slashing.getDescriptor(),
          cosmos_proto.Cosmos.getDescriptor(),
          cosmos.msg.v1.Msg.getDescriptor(),
          amino.Amino.getDescriptor(),
        });
    internal_static_cosmos_slashing_v1beta1_MsgUnjail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cosmos_slashing_v1beta1_MsgUnjail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_slashing_v1beta1_MsgUnjail_descriptor,
        new java.lang.String[] { "ValidatorAddr", });
    internal_static_cosmos_slashing_v1beta1_MsgUnjailResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cosmos_slashing_v1beta1_MsgUnjailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_slashing_v1beta1_MsgUnjailResponse_descriptor,
        new java.lang.String[] { });
    internal_static_cosmos_slashing_v1beta1_MsgUpdateParams_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cosmos_slashing_v1beta1_MsgUpdateParams_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_slashing_v1beta1_MsgUpdateParams_descriptor,
        new java.lang.String[] { "Authority", "Params", });
    internal_static_cosmos_slashing_v1beta1_MsgUpdateParamsResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_cosmos_slashing_v1beta1_MsgUpdateParamsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cosmos_slashing_v1beta1_MsgUpdateParamsResponse_descriptor,
        new java.lang.String[] { });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(amino.Amino.dontOmitempty);
    registry.add(amino.Amino.fieldName);
    registry.add(amino.Amino.name);
    registry.add(cosmos.msg.v1.Msg.service);
    registry.add(cosmos.msg.v1.Msg.signer);
    registry.add(cosmos_proto.Cosmos.scalar);
    registry.add(com.google.protobuf.GoGoProtos.equalAll);
    registry.add(com.google.protobuf.GoGoProtos.goprotoGetters);
    registry.add(com.google.protobuf.GoGoProtos.jsontag);
    registry.add(com.google.protobuf.GoGoProtos.nullable);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.GoGoProtos.getDescriptor();
    cosmos.slashing.v1beta1.Slashing.getDescriptor();
    cosmos_proto.Cosmos.getDescriptor();
    cosmos.msg.v1.Msg.getDescriptor();
    amino.Amino.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
