// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

package com.gg.protobuf;

/**
 * <pre>
 * A protocol buffer message type.
 * </pre>
 *
 * Protobuf type {@code google.protobuf.Type}
 */
public final class Type extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.protobuf.Type)
        TypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Type.newBuilder() to construct.
  private Type(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Type() {
    name_ = "";
    fields_ = java.util.Collections.emptyList();
    oneofs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    options_ = java.util.Collections.emptyList();
    syntax_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Type();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Type(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              fields_ = new java.util.ArrayList<Field>();
              mutable_bitField0_ |= 0x00000001;
            }
            fields_.add(
                input.readMessage(Field.parser(), extensionRegistry));
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) != 0)) {
              oneofs_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            oneofs_.add(s);
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000004) != 0)) {
              options_ = new java.util.ArrayList<Option>();
              mutable_bitField0_ |= 0x00000004;
            }
            options_.add(
                input.readMessage(Option.parser(), extensionRegistry));
            break;
          }
          case 42: {
            SourceContext.Builder subBuilder = null;
            if (sourceContext_ != null) {
              subBuilder = sourceContext_.toBuilder();
            }
            sourceContext_ = input.readMessage(SourceContext.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sourceContext_);
              sourceContext_ = subBuilder.buildPartial();
            }

            break;
          }
          case 48: {
            int rawValue = input.readEnum();

            syntax_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        fields_ = java.util.Collections.unmodifiableList(fields_);
      }
      if (((mutable_bitField0_ & 0x00000002) != 0)) {
        oneofs_ = oneofs_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) != 0)) {
        options_ = java.util.Collections.unmodifiableList(options_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return TypeProto.internal_static_google_protobuf_Type_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return TypeProto.internal_static_google_protobuf_Type_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Type.class, Type.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * The fully qualified message name.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * The fully qualified message name.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FIELDS_FIELD_NUMBER = 2;
  private java.util.List<Field> fields_;
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  @java.lang.Override
  public java.util.List<Field> getFieldsList() {
    return fields_;
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends FieldOrBuilder>
      getFieldsOrBuilderList() {
    return fields_;
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  @java.lang.Override
  public int getFieldsCount() {
    return fields_.size();
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  @java.lang.Override
  public Field getFields(int index) {
    return fields_.get(index);
  }
  /**
   * <pre>
   * The list of fields.
   * </pre>
   *
   * <code>repeated .google.protobuf.Field fields = 2;</code>
   */
  @java.lang.Override
  public FieldOrBuilder getFieldsOrBuilder(
      int index) {
    return fields_.get(index);
  }

  public static final int ONEOFS_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList oneofs_;
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   * @return A list containing the oneofs.
   */
  public com.google.protobuf.ProtocolStringList
      getOneofsList() {
    return oneofs_;
  }
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   * @return The count of oneofs.
   */
  public int getOneofsCount() {
    return oneofs_.size();
  }
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   * @param index The index of the element to return.
   * @return The oneofs at the given index.
   */
  public java.lang.String getOneofs(int index) {
    return oneofs_.get(index);
  }
  /**
   * <pre>
   * The list of types appearing in `oneof` definitions in this type.
   * </pre>
   *
   * <code>repeated string oneofs = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the oneofs at the given index.
   */
  public com.google.protobuf.ByteString
      getOneofsBytes(int index) {
    return oneofs_.getByteString(index);
  }

  public static final int OPTIONS_FIELD_NUMBER = 4;
  private java.util.List<Option> options_;
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  @java.lang.Override
  public java.util.List<Option> getOptionsList() {
    return options_;
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends OptionOrBuilder>
      getOptionsOrBuilderList() {
    return options_;
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  @java.lang.Override
  public int getOptionsCount() {
    return options_.size();
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  @java.lang.Override
  public Option getOptions(int index) {
    return options_.get(index);
  }
  /**
   * <pre>
   * The protocol buffer options.
   * </pre>
   *
   * <code>repeated .google.protobuf.Option options = 4;</code>
   */
  @java.lang.Override
  public OptionOrBuilder getOptionsOrBuilder(
      int index) {
    return options_.get(index);
  }

  public static final int SOURCE_CONTEXT_FIELD_NUMBER = 5;
  private SourceContext sourceContext_;
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>.google.protobuf.SourceContext source_context = 5;</code>
   * @return Whether the sourceContext field is set.
   */
  @java.lang.Override
  public boolean hasSourceContext() {
    return sourceContext_ != null;
  }
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>.google.protobuf.SourceContext source_context = 5;</code>
   * @return The sourceContext.
   */
  @java.lang.Override
  public SourceContext getSourceContext() {
    return sourceContext_ == null ? SourceContext.getDefaultInstance() : sourceContext_;
  }
  /**
   * <pre>
   * The source context.
   * </pre>
   *
   * <code>.google.protobuf.SourceContext source_context = 5;</code>
   */
  @java.lang.Override
  public SourceContextOrBuilder getSourceContextOrBuilder() {
    return getSourceContext();
  }

  public static final int SYNTAX_FIELD_NUMBER = 6;
  private int syntax_;
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>.google.protobuf.Syntax syntax = 6;</code>
   * @return The enum numeric value on the wire for syntax.
   */
  @java.lang.Override public int getSyntaxValue() {
    return syntax_;
  }
  /**
   * <pre>
   * The source syntax.
   * </pre>
   *
   * <code>.google.protobuf.Syntax syntax = 6;</code>
   * @return The syntax.
   */
  @java.lang.Override public Syntax getSyntax() {
    @SuppressWarnings("deprecation")
    Syntax result = Syntax.valueOf(syntax_);
    return result == null ? Syntax.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    for (int i = 0; i < fields_.size(); i++) {
      output.writeMessage(2, fields_.get(i));
    }
    for (int i = 0; i < oneofs_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, oneofs_.getRaw(i));
    }
    for (int i = 0; i < options_.size(); i++) {
      output.writeMessage(4, options_.get(i));
    }
    if (sourceContext_ != null) {
      output.writeMessage(5, getSourceContext());
    }
    if (syntax_ != Syntax.SYNTAX_PROTO2.getNumber()) {
      output.writeEnum(6, syntax_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    for (int i = 0; i < fields_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, fields_.get(i));
    }
    {
      int dataSize = 0;
      for (int i = 0; i < oneofs_.size(); i++) {
        dataSize += computeStringSizeNoTag(oneofs_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getOneofsList().size();
    }
    for (int i = 0; i < options_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, options_.get(i));
    }
    if (sourceContext_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getSourceContext());
    }
    if (syntax_ != Syntax.SYNTAX_PROTO2.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(6, syntax_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Type)) {
      return super.equals(obj);
    }
    Type other = (Type) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getFieldsList()
        .equals(other.getFieldsList())) return false;
    if (!getOneofsList()
        .equals(other.getOneofsList())) return false;
    if (!getOptionsList()
        .equals(other.getOptionsList())) return false;
    if (hasSourceContext() != other.hasSourceContext()) return false;
    if (hasSourceContext()) {
      if (!getSourceContext()
          .equals(other.getSourceContext())) return false;
    }
    if (syntax_ != other.syntax_) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    if (getFieldsCount() > 0) {
      hash = (37 * hash) + FIELDS_FIELD_NUMBER;
      hash = (53 * hash) + getFieldsList().hashCode();
    }
    if (getOneofsCount() > 0) {
      hash = (37 * hash) + ONEOFS_FIELD_NUMBER;
      hash = (53 * hash) + getOneofsList().hashCode();
    }
    if (getOptionsCount() > 0) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptionsList().hashCode();
    }
    if (hasSourceContext()) {
      hash = (37 * hash) + SOURCE_CONTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getSourceContext().hashCode();
    }
    hash = (37 * hash) + SYNTAX_FIELD_NUMBER;
    hash = (53 * hash) + syntax_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Type parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Type parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Type parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Type parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Type parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Type parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Type parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Type parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Type parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Type parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Type parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Type parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Type prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * A protocol buffer message type.
   * </pre>
   *
   * Protobuf type {@code google.protobuf.Type}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.protobuf.Type)
          com.gg.protobuf.TypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TypeProto.internal_static_google_protobuf_Type_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TypeProto.internal_static_google_protobuf_Type_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Type.class, Type.Builder.class);
    }

    // Construct using com.google.protobuf.Type.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFieldsFieldBuilder();
        getOptionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      if (fieldsBuilder_ == null) {
        fields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        fieldsBuilder_.clear();
      }
      oneofs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        optionsBuilder_.clear();
      }
      if (sourceContextBuilder_ == null) {
        sourceContext_ = null;
      } else {
        sourceContext_ = null;
        sourceContextBuilder_ = null;
      }
      syntax_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return TypeProto.internal_static_google_protobuf_Type_descriptor;
    }

    @java.lang.Override
    public Type getDefaultInstanceForType() {
      return Type.getDefaultInstance();
    }

    @java.lang.Override
    public Type build() {
      Type result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Type buildPartial() {
      Type result = new Type(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      if (fieldsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          fields_ = java.util.Collections.unmodifiableList(fields_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fields_ = fields_;
      } else {
        result.fields_ = fieldsBuilder_.build();
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        oneofs_ = oneofs_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.oneofs_ = oneofs_;
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          options_ = java.util.Collections.unmodifiableList(options_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.options_ = options_;
      } else {
        result.options_ = optionsBuilder_.build();
      }
      if (sourceContextBuilder_ == null) {
        result.sourceContext_ = sourceContext_;
      } else {
        result.sourceContext_ = sourceContextBuilder_.build();
      }
      result.syntax_ = syntax_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Type) {
        return mergeFrom((Type)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Type other) {
      if (other == Type.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (fieldsBuilder_ == null) {
        if (!other.fields_.isEmpty()) {
          if (fields_.isEmpty()) {
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFieldsIsMutable();
            fields_.addAll(other.fields_);
          }
          onChanged();
        }
      } else {
        if (!other.fields_.isEmpty()) {
          if (fieldsBuilder_.isEmpty()) {
            fieldsBuilder_.dispose();
            fieldsBuilder_ = null;
            fields_ = other.fields_;
            bitField0_ = (bitField0_ & ~0x00000001);
            fieldsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFieldsFieldBuilder() : null;
          } else {
            fieldsBuilder_.addAllMessages(other.fields_);
          }
        }
      }
      if (!other.oneofs_.isEmpty()) {
        if (oneofs_.isEmpty()) {
          oneofs_ = other.oneofs_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureOneofsIsMutable();
          oneofs_.addAll(other.oneofs_);
        }
        onChanged();
      }
      if (optionsBuilder_ == null) {
        if (!other.options_.isEmpty()) {
          if (options_.isEmpty()) {
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureOptionsIsMutable();
            options_.addAll(other.options_);
          }
          onChanged();
        }
      } else {
        if (!other.options_.isEmpty()) {
          if (optionsBuilder_.isEmpty()) {
            optionsBuilder_.dispose();
            optionsBuilder_ = null;
            options_ = other.options_;
            bitField0_ = (bitField0_ & ~0x00000004);
            optionsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOptionsFieldBuilder() : null;
          } else {
            optionsBuilder_.addAllMessages(other.options_);
          }
        }
      }
      if (other.hasSourceContext()) {
        mergeSourceContext(other.getSourceContext());
      }
      if (other.syntax_ != 0) {
        setSyntaxValue(other.getSyntaxValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Type parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Type) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * The fully qualified message name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * The fully qualified message name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * The fully qualified message name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The fully qualified message name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The fully qualified message name.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.util.List<Field> fields_ =
      java.util.Collections.emptyList();
    private void ensureFieldsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        fields_ = new java.util.ArrayList<Field>(fields_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            Field, Field.Builder, FieldOrBuilder> fieldsBuilder_;

    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public java.util.List<Field> getFieldsList() {
      if (fieldsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fields_);
      } else {
        return fieldsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public int getFieldsCount() {
      if (fieldsBuilder_ == null) {
        return fields_.size();
      } else {
        return fieldsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Field getFields(int index) {
      if (fieldsBuilder_ == null) {
        return fields_.get(index);
      } else {
        return fieldsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder setFields(
        int index, Field value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.set(index, value);
        onChanged();
      } else {
        fieldsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder setFields(
        int index, Field.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.set(index, builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder addFields(Field value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.add(value);
        onChanged();
      } else {
        fieldsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder addFields(
        int index, Field value) {
      if (fieldsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFieldsIsMutable();
        fields_.add(index, value);
        onChanged();
      } else {
        fieldsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder addFields(
        Field.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.add(builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder addFields(
        int index, Field.Builder builderForValue) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.add(index, builderForValue.build());
        onChanged();
      } else {
        fieldsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder addAllFields(
        java.lang.Iterable<? extends Field> values) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fields_);
        onChanged();
      } else {
        fieldsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder clearFields() {
      if (fieldsBuilder_ == null) {
        fields_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        fieldsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Builder removeFields(int index) {
      if (fieldsBuilder_ == null) {
        ensureFieldsIsMutable();
        fields_.remove(index);
        onChanged();
      } else {
        fieldsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Field.Builder getFieldsBuilder(
        int index) {
      return getFieldsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public FieldOrBuilder getFieldsOrBuilder(
        int index) {
      if (fieldsBuilder_ == null) {
        return fields_.get(index);  } else {
        return fieldsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public java.util.List<? extends FieldOrBuilder>
         getFieldsOrBuilderList() {
      if (fieldsBuilder_ != null) {
        return fieldsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fields_);
      }
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Field.Builder addFieldsBuilder() {
      return getFieldsFieldBuilder().addBuilder(
          Field.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public Field.Builder addFieldsBuilder(
        int index) {
      return getFieldsFieldBuilder().addBuilder(
          index, Field.getDefaultInstance());
    }
    /**
     * <pre>
     * The list of fields.
     * </pre>
     *
     * <code>repeated .google.protobuf.Field fields = 2;</code>
     */
    public java.util.List<Field.Builder>
         getFieldsBuilderList() {
      return getFieldsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            Field, Field.Builder, FieldOrBuilder>
        getFieldsFieldBuilder() {
      if (fieldsBuilder_ == null) {
        fieldsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                Field, Field.Builder, FieldOrBuilder>(
                fields_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        fields_ = null;
      }
      return fieldsBuilder_;
    }

    private com.google.protobuf.LazyStringList oneofs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureOneofsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        oneofs_ = new com.google.protobuf.LazyStringArrayList(oneofs_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @return A list containing the oneofs.
     */
    public com.google.protobuf.ProtocolStringList
        getOneofsList() {
      return oneofs_.getUnmodifiableView();
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @return The count of oneofs.
     */
    public int getOneofsCount() {
      return oneofs_.size();
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @param index The index of the element to return.
     * @return The oneofs at the given index.
     */
    public java.lang.String getOneofs(int index) {
      return oneofs_.get(index);
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the oneofs at the given index.
     */
    public com.google.protobuf.ByteString
        getOneofsBytes(int index) {
      return oneofs_.getByteString(index);
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @param index The index to set the value at.
     * @param value The oneofs to set.
     * @return This builder for chaining.
     */
    public Builder setOneofs(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOneofsIsMutable();
      oneofs_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @param value The oneofs to add.
     * @return This builder for chaining.
     */
    public Builder addOneofs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureOneofsIsMutable();
      oneofs_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @param values The oneofs to add.
     * @return This builder for chaining.
     */
    public Builder addAllOneofs(
        java.lang.Iterable<java.lang.String> values) {
      ensureOneofsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, oneofs_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearOneofs() {
      oneofs_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The list of types appearing in `oneof` definitions in this type.
     * </pre>
     *
     * <code>repeated string oneofs = 3;</code>
     * @param value The bytes of the oneofs to add.
     * @return This builder for chaining.
     */
    public Builder addOneofsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureOneofsIsMutable();
      oneofs_.add(value);
      onChanged();
      return this;
    }

    private java.util.List<Option> options_ =
      java.util.Collections.emptyList();
    private void ensureOptionsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        options_ = new java.util.ArrayList<Option>(options_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            Option, Option.Builder, OptionOrBuilder> optionsBuilder_;

    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public java.util.List<Option> getOptionsList() {
      if (optionsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(options_);
      } else {
        return optionsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public int getOptionsCount() {
      if (optionsBuilder_ == null) {
        return options_.size();
      } else {
        return optionsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Option getOptions(int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);
      } else {
        return optionsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder setOptions(
        int index, Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.set(index, value);
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder setOptions(
        int index, Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.set(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder addOptions(Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder addOptions(
        int index, Option value) {
      if (optionsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOptionsIsMutable();
        options_.add(index, value);
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder addOptions(
        Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder addOptions(
        int index, Option.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.add(index, builderForValue.build());
        onChanged();
      } else {
        optionsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder addAllOptions(
        java.lang.Iterable<? extends Option> values) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, options_);
        onChanged();
      } else {
        optionsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder clearOptions() {
      if (optionsBuilder_ == null) {
        options_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        optionsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Builder removeOptions(int index) {
      if (optionsBuilder_ == null) {
        ensureOptionsIsMutable();
        options_.remove(index);
        onChanged();
      } else {
        optionsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Option.Builder getOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public OptionOrBuilder getOptionsOrBuilder(
        int index) {
      if (optionsBuilder_ == null) {
        return options_.get(index);  } else {
        return optionsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public java.util.List<? extends OptionOrBuilder>
         getOptionsOrBuilderList() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(options_);
      }
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Option.Builder addOptionsBuilder() {
      return getOptionsFieldBuilder().addBuilder(
          Option.getDefaultInstance());
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public Option.Builder addOptionsBuilder(
        int index) {
      return getOptionsFieldBuilder().addBuilder(
          index, Option.getDefaultInstance());
    }
    /**
     * <pre>
     * The protocol buffer options.
     * </pre>
     *
     * <code>repeated .google.protobuf.Option options = 4;</code>
     */
    public java.util.List<Option.Builder>
         getOptionsBuilderList() {
      return getOptionsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            Option, Option.Builder, OptionOrBuilder>
        getOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                Option, Option.Builder, OptionOrBuilder>(
                options_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }

    private SourceContext sourceContext_;
    private com.google.protobuf.SingleFieldBuilderV3<
            SourceContext, SourceContext.Builder, SourceContextOrBuilder> sourceContextBuilder_;
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 5;</code>
     * @return Whether the sourceContext field is set.
     */
    public boolean hasSourceContext() {
      return sourceContextBuilder_ != null || sourceContext_ != null;
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 5;</code>
     * @return The sourceContext.
     */
    public SourceContext getSourceContext() {
      if (sourceContextBuilder_ == null) {
        return sourceContext_ == null ? SourceContext.getDefaultInstance() : sourceContext_;
      } else {
        return sourceContextBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 5;</code>
     */
    public Builder setSourceContext(SourceContext value) {
      if (sourceContextBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sourceContext_ = value;
        onChanged();
      } else {
        sourceContextBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 5;</code>
     */
    public Builder setSourceContext(
        SourceContext.Builder builderForValue) {
      if (sourceContextBuilder_ == null) {
        sourceContext_ = builderForValue.build();
        onChanged();
      } else {
        sourceContextBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 5;</code>
     */
    public Builder mergeSourceContext(SourceContext value) {
      if (sourceContextBuilder_ == null) {
        if (sourceContext_ != null) {
          sourceContext_ =
            SourceContext.newBuilder(sourceContext_).mergeFrom(value).buildPartial();
        } else {
          sourceContext_ = value;
        }
        onChanged();
      } else {
        sourceContextBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 5;</code>
     */
    public Builder clearSourceContext() {
      if (sourceContextBuilder_ == null) {
        sourceContext_ = null;
        onChanged();
      } else {
        sourceContext_ = null;
        sourceContextBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 5;</code>
     */
    public SourceContext.Builder getSourceContextBuilder() {
      
      onChanged();
      return getSourceContextFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 5;</code>
     */
    public SourceContextOrBuilder getSourceContextOrBuilder() {
      if (sourceContextBuilder_ != null) {
        return sourceContextBuilder_.getMessageOrBuilder();
      } else {
        return sourceContext_ == null ?
            SourceContext.getDefaultInstance() : sourceContext_;
      }
    }
    /**
     * <pre>
     * The source context.
     * </pre>
     *
     * <code>.google.protobuf.SourceContext source_context = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            SourceContext, SourceContext.Builder, SourceContextOrBuilder>
        getSourceContextFieldBuilder() {
      if (sourceContextBuilder_ == null) {
        sourceContextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                SourceContext, SourceContext.Builder, SourceContextOrBuilder>(
                getSourceContext(),
                getParentForChildren(),
                isClean());
        sourceContext_ = null;
      }
      return sourceContextBuilder_;
    }

    private int syntax_ = 0;
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>.google.protobuf.Syntax syntax = 6;</code>
     * @return The enum numeric value on the wire for syntax.
     */
    @java.lang.Override public int getSyntaxValue() {
      return syntax_;
    }
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>.google.protobuf.Syntax syntax = 6;</code>
     * @param value The enum numeric value on the wire for syntax to set.
     * @return This builder for chaining.
     */
    public Builder setSyntaxValue(int value) {
      
      syntax_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>.google.protobuf.Syntax syntax = 6;</code>
     * @return The syntax.
     */
    @java.lang.Override
    public Syntax getSyntax() {
      @SuppressWarnings("deprecation")
      Syntax result = Syntax.valueOf(syntax_);
      return result == null ? Syntax.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>.google.protobuf.Syntax syntax = 6;</code>
     * @param value The syntax to set.
     * @return This builder for chaining.
     */
    public Builder setSyntax(Syntax value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      syntax_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The source syntax.
     * </pre>
     *
     * <code>.google.protobuf.Syntax syntax = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearSyntax() {
      
      syntax_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.protobuf.Type)
  }

  // @@protoc_insertion_point(class_scope:google.protobuf.Type)
  private static final Type DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Type();
  }

  public static Type getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Type>
      PARSER = new com.google.protobuf.AbstractParser<Type>() {
    @java.lang.Override
    public Type parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Type(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Type> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Type> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Type getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

